# MySQL 驱动
jdbc.driver=com.mysql.cj.jdbc.Driver
# JDBC URL
jdbc.url=jdbc:mysql://127.0.0.1:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
# 数据库用户名
jdbc.username=root
# 数据库用户名密码
jdbc.password=root@123456
# 实体类所在包
#package.model = com.lsj.demo.entity
#  mapper 所在包
#package.mapper = com.lsj.demo.mapper
#  mapper xml 文件所在包 默认存储在 resources 目录下
package.xml=mapper
# 初始化连接大小
initialSize=1
# 连接池最大数量
maxActive=10
# 连接池最小空闲
minIdle=2
# 获取连接最大等待时间
maxWait=60000
